### ISSUE TITLE
Add support for AbortController

### ISSUE THREAD

**Issue by pimterry** [jonnyreeves/fetch-readablestream#6]
AbortController is the new standard way to cancel a running fetch request. It's got about 60% support already (https://caniuse.com/#feat=abortcontroller), but it doesn't work when fetching with this library, even in some browsers that do support it, because of the XHR transport.

Being able to cancel long-running requests is a super useful feature imo, especially when streaming. Would you be interested in a PR that adds support for AbortController to XHR-transported requests too? https://github.com/mo/abortcontroller-polyfill/blob/master/src/abortableFetch.js is a good example of how to patch Fetch to support this in environments where it doesn't, and it's fairly simple. Afaict it's basically just:

* If you pass a `signal` argument, check `signal.aborted`, and don't send anything if it's set initially.
* Subscribe to `abort` events from the signal object.
* Any time a request is aborted, cancel the underlying request, and reject its promises with an `AbortError`.

Interested? I'd be happy to help out with a PR, if it's likely to be accepted.

**Comment by jonnyreeves** [comment]
Would gladly accept and merge it. Thanks!
